#import <PhotosUICore/PXCuratedLibraryAssetsDataSourceManagerConfiguration.h>

NS_ASSUME_NONNULL_BEGIN

@interface _PXPhotoLibraryCuratedLibraryAssetsDataSourceManagerConfiguration : PXCuratedLibraryAssetsDataSourceManagerConfiguration
@end

NS_ASSUME_NONNULL_END